/**
 * 국방 AI(AI+IT) 뉴스레터 아카이브 설정 파일
 *
 * 새 뉴스레터 추가 방법:
 * 1. data/ 폴더에 newsletter-{호수}.js 파일 생성
 * 2. 아래 NEWSLETTER_FILES 배열 맨 앞에 파일 경로 추가
 *    (최신 호수가 배열 앞에 오도록 내림차순 정렬)
 */
window.NEWSLETTER_CONFIG = {
  // 로드할 뉴스레터 파일 목록 (최신 순으로 정렬)
  files: [
    "data/newsletter-59.js",
    "data/newsletter-58.js",
    "data/newsletter-57.js",
    "data/newsletter-56.js",
    "data/newsletter-55.js",
    "data/newsletter-54.js",
    "data/newsletter-53.js",
    "data/newsletter-52.js",
    "data/newsletter-51.js",
    "data/newsletter-50.js",
    "data/newsletter-49.js",
    "data/newsletter-48.js",
    "data/newsletter-47.js",
    "data/newsletter-46.js",
    "data/newsletter-45.js",
    "data/newsletter-44.js",
    "data/newsletter-43.js",
    "data/newsletter-42.js",
    "data/newsletter-41.js",
    "data/newsletter-40.js",
    "data/newsletter-39.js",
    "data/newsletter-38.js",
    "data/newsletter-37.js",
    "data/newsletter-36.js",
    "data/newsletter-35.js",
    "data/newsletter-34.js",
    "data/newsletter-33.js",
    "data/newsletter-32.js",
    "data/newsletter-31.js",
    "data/newsletter-30.js",
    "data/newsletter-29.js",
    "data/newsletter-28.js",
    "data/newsletter-27.js",
    "data/newsletter-26.js",
    "data/newsletter-25.js",
    "data/newsletter-24.js",
    "data/newsletter-23.js",
    "data/newsletter-22.js",
    "data/newsletter-21.js",
    "data/newsletter-20.js",
    "data/newsletter-19.js",
    "data/newsletter-18.js",
    "data/newsletter-17.js",
    "data/newsletter-16.js",
    "data/newsletter-15.js",
    "data/newsletter-14.js",
    "data/newsletter-13.js",
    "data/newsletter-12.js",
    "data/newsletter-11.js",
    "data/newsletter-10.js",
    "data/newsletter-9.js",
    "data/newsletter-8.js",
    "data/newsletter-7.js",
    "data/newsletter-6.js",
    "data/newsletter-5.js",
    "data/newsletter-4.js",
    "data/newsletter-3.js",
    "data/newsletter-2.js",
    "data/newsletter-1.js",
  ],

  // 사이트 정보
  siteTitle: "국방 AI(AI+IT) 뉴스레터 아카이브",
  siteSubtitle: "매주 국방 AI 및 정보기술 관련 기사 검색 데이터베이스",
  author: "Seungbae Sim (Crayon) with ChatGPT + Gemini + Claude + Perplexity",
};
