/**
 * 국방 AI(AI+IT) 뉴스레터 아카이브 — 온톨로지 엔터티 사전
 *
 * ontology.html이 config.js의 뉴스레터 데이터를 읽은 뒤 이 사전으로 기사마다 오브젝트를 찾습니다.
 * 새 호를 추가할 때는 이 파일을 고치지 않아도 됩니다. 새로 자주 등장하는 기관·기업·인물·사업·정책이
 * 있으면 ENTITIES에 항목을 추가하고 VERSION 날짜를 바꾸세요.
 *
 * 항목 형식: { id, t: 유형, n: 한글 이름, e: 영문 이름, a: [별칭], p: {속성}, rel?: [관련 id], hub?: true }
 *   유형(t): country | org | company | person | model | program | policy | domain | event
 * 별칭 규칙: '=X'는 대소문자 구분 / 영문 별칭은 대소문자 무시·단어 경계에서만 일치
 *   한글 포함 별칭은 부분 일치(2자 이하는 그대로, 3자 이상은 공백을 지우고 비교) / RegExp는 그대로 적용
 */
(function (root) {
const R = (s, f = '') => new RegExp(s, f);
const FOREIGN = '(?:영국|이스라엘|우크라이나|중국|러시아|태국|캐나다|한국|일본|프랑스|독일|대만|호주|폴란드|핀란드|에스토니아|스웨덴|튀르키예|네덜란드|북한|이란|인도|유럽|나토|NATO|PLA|스페인|이탈리아|사우디|UAE)';
const nf = term => R('(?<!' + FOREIGN + '\\s?)' + term);

const ENTITIES = [
  // ---------------- 국가·지역 ----------------
  { id: 'us', t: 'country', n: '미국', e: 'United States', a: [], p: { bloc: '미국' }, hub: true },
  { id: 'cn', t: 'country', n: '중국', e: 'China', a: ['중국', 'China', 'Chinese', '=PRC', '베이징', 'Beijing', '시진핑', 'Xi Jinping', '中'], p: { bloc: '전략 경쟁국' } },
  { id: 'ru', t: 'country', n: '러시아', e: 'Russia', a: ['러시아', 'Russia', 'Russian', '크렘린', 'Kremlin', '푸틴', 'Putin'], p: { bloc: '적대국' } },
  { id: 'ua', t: 'country', n: '우크라이나', e: 'Ukraine', a: ['우크라이나', 'Ukraine', 'Ukrainian', 'UkrAIne', '젤렌스키', 'Zelensky'], p: { bloc: '분쟁 당사국(우방)' } },
  { id: 'il', t: 'country', n: '이스라엘', e: 'Israel', a: ['이스라엘', 'Israel', 'Israeli'], p: { bloc: '동맹·우방' } },
  { id: 'ir', t: 'country', n: '이란', e: 'Iran', a: [R('(?:^|[^가-힣]|대)이란'), 'Iran', 'Iranian', '테헤란'], p: { bloc: '적대국' } },
  { id: 'kr', t: 'country', n: '한국', e: 'South Korea', a: ['대한민국', '한국', '한미', '=ROK', 'South Korea', 'Republic of Korea', '주한미군'], p: { bloc: '동맹·우방' } },
  { id: 'kp', t: 'country', n: '북한', e: 'North Korea', a: ['북한', 'North Korea', '=DPRK', '김정은'], p: { bloc: '적대국' } },
  { id: 'tw', t: 'country', n: '대만', e: 'Taiwan', a: ['대만', 'Taiwan', '타이완', '타이베이', 'Taipei'], p: { bloc: '우방' } },
  { id: 'jp', t: 'country', n: '일본', e: 'Japan', a: ['일본', 'Japan', 'Japanese'], p: { bloc: '동맹·우방' } },
  { id: 'uk', t: 'country', n: '영국', e: 'United Kingdom', a: ['영국', '=UK', 'United Kingdom', 'Britain', 'British', '=Dstl'], p: { bloc: '동맹·우방' } },
  { id: 'fr', t: 'country', n: '프랑스', e: 'France', a: ['프랑스', 'France', 'French'], p: { bloc: '동맹·우방' } },
  { id: 'de', t: 'country', n: '독일', e: 'Germany', a: ['독일', 'Germany', 'German'], p: { bloc: '동맹·우방' } },
  { id: 'fi', t: 'country', n: '핀란드', e: 'Finland', a: ['핀란드', 'Finland', 'Finnish'], p: { bloc: '동맹·우방' } },
  { id: 'ee', t: 'country', n: '에스토니아', e: 'Estonia', a: ['에스토니아', 'Estonia', 'Estonian'], p: { bloc: '동맹·우방' } },
  { id: 'se', t: 'country', n: '스웨덴', e: 'Sweden', a: ['스웨덴', 'Sweden', 'Swedish'], p: { bloc: '동맹·우방' } },
  { id: 'ca', t: 'country', n: '캐나다', e: 'Canada', a: ['캐나다', 'Canada', 'Canadian'], p: { bloc: '동맹·우방' } },
  { id: 'au', t: 'country', n: '호주', e: 'Australia', a: ['호주', 'Australia', 'Australian'], p: { bloc: '동맹·우방' } },
  { id: 'pl', t: 'country', n: '폴란드', e: 'Poland', a: ['폴란드', 'Poland', '=Polish'], p: { bloc: '동맹·우방' } },
  { id: 'nl', t: 'country', n: '네덜란드', e: 'Netherlands', a: ['네덜란드', 'Netherlands', 'Dutch'], p: { bloc: '동맹·우방' } },
  { id: 'tr', t: 'country', n: '튀르키예', e: 'Türkiye', a: ['튀르키예', '터키', 'Turkey', 'Türkiye', 'Turkish'], p: { bloc: 'NATO 회원국' } },
  { id: 'ae', t: 'country', n: 'UAE', e: 'United Arab Emirates', a: ['=UAE', '아랍에미리트', '에미리트'], p: { bloc: '우방' } },
  { id: 'th', t: 'country', n: '태국', e: 'Thailand', a: ['태국', 'Thailand'], p: { bloc: '우방' } },
  { id: 'ro', t: 'country', n: '루마니아', e: 'Romania', a: ['루마니아', 'Romania'], p: { bloc: '동맹·우방' } },
  { id: 'indopac', t: 'country', n: '인도태평양(지역)', e: 'Indo-Pacific', a: [R('인도[-·\\s]?태평양(?!\\s?사령)'), 'Indo-Pacific', '인태 지역', '인태지역'], p: { bloc: '지역' } },

  // ---------------- 기관 ----------------
  { id: 'dod', t: 'org', n: '미 국방부(전쟁부)', e: 'Department of Defense / War', a: ['=DoD', '=DOD', '=DoW', 'Pentagon', 'Department of War', 'Department of Defense', 'War Department', '펜타곤', '전쟁부', '=OSD', nf('국방부(?!장)')], p: { cat: '국방 본부', country: 'us' } },
  { id: 'cdao', t: 'org', n: 'CDAO(최고디지털·AI책임자실)', e: 'Chief Digital and AI Office', a: ['=CDAO', 'Chief Digital and AI', 'Chief Digital and Artificial Intelligence', '최고디지털'], p: { cat: '국방 기관', country: 'us', parent: 'dod' } },
  { id: 'army', t: 'org', n: '미 육군', e: 'U.S. Army', a: ['U.S. Army', 'US Army', '=Army', nf('육군')], p: { cat: '군종', country: 'us', parent: 'dod' } },
  { id: 'navy', t: 'org', n: '미 해군', e: 'U.S. Navy', a: ['U.S. Navy', 'US Navy', '=Navy', '=DoN', 'Department of the Navy', nf('해군')], p: { cat: '군종', country: 'us', parent: 'dod' } },
  { id: 'usaf', t: 'org', n: '미 공군', e: 'U.S. Air Force', a: ['=USAF', 'U.S. Air Force', 'US Air Force', 'Air Force', '=DAF', 'Department of the Air Force', nf('공군')], p: { cat: '군종', country: 'us', parent: 'dod' } },
  { id: 'usmc', t: 'org', n: '미 해병대', e: 'U.S. Marine Corps', a: ['=USMC', 'Marine Corps', 'Marines', '해병대'], p: { cat: '군종', country: 'us', parent: 'dod' } },
  { id: 'ussf', t: 'org', n: '미 우주군', e: 'U.S. Space Force', a: ['Space Force', '=USSF', '우주군'], p: { cat: '군종', country: 'us', parent: 'dod' } },
  { id: 'jcs', t: 'org', n: '합동참모본부', e: 'Joint Chiefs of Staff', a: ['Joint Chiefs', '=JCS', '합참', '합동참모'], p: { cat: '국방 기관', country: 'us', parent: 'dod' } },
  { id: 'indopacom', t: 'org', n: '인도태평양사령부', e: 'INDOPACOM', a: ['=INDOPACOM', '=USINDOPACOM', '인도태평양사령부', '인태사령부', '인도태평양사령관', '인도-태평양 사령부'], p: { cat: '통합전투사령부', country: 'us', parent: 'dod' } },
  { id: 'centcom', t: 'org', n: '중부사령부', e: 'CENTCOM', a: ['=CENTCOM', '중부사령부', '중부군사령부'], p: { cat: '통합전투사령부', country: 'us', parent: 'dod' } },
  { id: 'socom', t: 'org', n: '특수작전사령부', e: 'SOCOM', a: ['=SOCOM', '=USSOCOM', '특수작전사령부', '특전사'], p: { cat: '통합전투사령부', country: 'us', parent: 'dod' } },
  { id: 'cybercom', t: 'org', n: '사이버사령부', e: 'U.S. Cyber Command', a: ['=CYBERCOM', '=USCYBERCOM', 'Cyber Command', R('(?<!육군\\s?|공군\\s?|해군\\s?)사이버사령부')], p: { cat: '통합전투사령부', country: 'us', parent: 'dod' } },
  { id: 'stratcom', t: 'org', n: '전략사령부', e: 'STRATCOM', a: ['=STRATCOM', '=USSTRATCOM', '전략사령부'], p: { cat: '통합전투사령부', country: 'us', parent: 'dod' } },
  { id: 'autowarcom', t: 'org', n: '자율전투사령부(AUTOWARCOM)', e: 'Autonomous Warfare Command', a: ['=AUTOWARCOM', 'Autonomous Warfare Command', '자율전투사령부'], p: { cat: '통합전투사령부(창설 예정)', country: 'us', parent: 'dod' } },
  { id: 'arcyber', t: 'org', n: '육군 사이버사령부', e: 'ARCYBER', a: ['=ARCYBER', 'Army Cyber', '육군 사이버사령부'], p: { cat: '군종 예하', country: 'us', parent: 'army' } },
  { id: 'diu', t: 'org', n: '국방혁신단(DIU)', e: 'Defense Innovation Unit', a: ['=DIU', 'Defense Innovation Unit', '국방혁신단', '국방혁신부'], p: { cat: '국방 기관', country: 'us', parent: 'dod' } },
  { id: 'darpa', t: 'org', n: 'DARPA', e: 'DARPA', a: ['=DARPA', '방위고등연구계획국', '고등연구계획국'], p: { cat: '국방 기관', country: 'us', parent: 'dod' } },
  { id: 'disa', t: 'org', n: '국방정보시스템국(DISA)', e: 'DISA', a: ['=DISA', '국방정보시스템국'], p: { cat: '국방 기관', country: 'us', parent: 'dod' } },
  { id: 'dla', t: 'org', n: '국방병참지원국(DLA)', e: 'Defense Logistics Agency', a: ['=DLA', 'Defense Logistics Agency', '국방병참지원국', '국방군수국'], p: { cat: '국방 기관', country: 'us', parent: 'dod' } },
  { id: 'dcsa', t: 'org', n: '국방방첩보안국(DCSA)', e: 'DCSA', a: ['=DCSA'], p: { cat: '국방 기관', country: 'us', parent: 'dod' } },
  { id: 'jiatf401', t: 'org', n: 'JIATF-401(대드론 합동TF)', e: 'JIATF-401', a: ['=JIATF', '대드론 태스크포스', '대드론 TF', '대드론 합동', '합동기관간', 'Joint Interagency Task Force'], p: { cat: '국방 기관', country: 'us', parent: 'dod' } },
  { id: 'nps', t: 'org', n: '해군대학원(NPS)', e: 'Naval Postgraduate School', a: ['=NPS', 'Naval Postgraduate School', '해군대학원'], p: { cat: '군종 예하', country: 'us', parent: 'navy' } },
  { id: 'afrl', t: 'org', n: '공군연구소(AFRL)', e: 'AFRL', a: ['=AFRL', '공군연구소'], p: { cat: '군종 예하', country: 'us', parent: 'usaf' } },
  { id: 'nsa', t: 'org', n: '국가안보국(NSA)', e: 'NSA', a: ['=NSA', '국가안보국'], p: { cat: '정보기관', country: 'us' } },
  { id: 'cia', t: 'org', n: 'CIA', e: 'CIA', a: ['=CIA', '중앙정보국'], p: { cat: '정보기관', country: 'us' } },
  { id: 'nga', t: 'org', n: '국가지리정보국(NGA)', e: 'NGA', a: ['=NGA', '국가지리정보국'], p: { cat: '정보기관', country: 'us' } },
  { id: 'dia', t: 'org', n: '국방정보국(DIA)', e: 'DIA', a: ['=DIA', '국방정보국'], p: { cat: '정보기관', country: 'us' } },
  { id: 'nro', t: 'org', n: '국가정찰국(NRO)', e: 'NRO', a: ['=NRO', '국가정찰국'], p: { cat: '정보기관', country: 'us' } },
  { id: 'odni', t: 'org', n: '국가정보장실(ODNI)', e: 'ODNI', a: ['=ODNI', '=DNI', '국가정보장', '국가정보국장'], p: { cat: '정보기관', country: 'us' } },
  { id: 'wh', t: 'org', n: '백악관', e: 'White House', a: ['White House', '백악관', '=EOP'], p: { cat: '행정부', country: 'us' } },
  { id: 'omb', t: 'org', n: '관리예산처(OMB)', e: 'OMB', a: ['=OMB', '관리예산처', '관리예산국', '예산관리국', '예산관리처', '연방 CIO', 'Federal CIO'], p: { cat: '행정부', country: 'us', parent: 'wh' } },
  { id: 'ostp', t: 'org', n: '과학기술정책실(OSTP)', e: 'OSTP', a: ['=OSTP', '과학기술정책실', '과학기술정책국', '과학기술자문실'], p: { cat: '행정부', country: 'us', parent: 'wh' } },
  { id: 'oncd', t: 'org', n: '국가사이버국장실(ONCD)', e: 'ONCD', a: ['=ONCD', '=NCD', '국가사이버국장', '국가사이버국'], p: { cat: '행정부', country: 'us', parent: 'wh' } },
  { id: 'doge', t: 'org', n: '정부효율부(DOGE)', e: 'DOGE', a: ['=DOGE', '정부효율부', '정부효율성부'], p: { cat: '행정부', country: 'us', parent: 'wh' } },
  { id: 'gsa', t: 'org', n: '연방조달청(GSA)', e: 'GSA', a: ['=GSA', '조달청', '연방조달청', '일반조달청', '총무청', '연방총무청'], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'dhs', t: 'org', n: '국토안보부(DHS)', e: 'DHS', a: ['=DHS', '국토안보부', 'Homeland Security'], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'cisa', t: 'org', n: '사이버보안·인프라보안국(CISA)', e: 'CISA', a: ['=CISA', '사이버보안·인프라보안국', '사이버보안인프라보안국', '사이버안보·인프라보안청'], p: { cat: '연방 민간기관', country: 'us', parent: 'dhs' } },
  { id: 'cbp', t: 'org', n: '세관국경보호청(CBP)', e: 'CBP', a: ['=CBP', '=USBP', '세관국경보호청', '관세국경보호청', '국경순찰대', '국경 보안'], p: { cat: '연방 민간기관', country: 'us', parent: 'dhs' } },
  { id: 'tsa', t: 'org', n: '교통보안청(TSA)', e: 'TSA', a: ['=TSA', '교통보안청'], p: { cat: '연방 민간기관', country: 'us', parent: 'dhs' } },
  { id: 'doj', t: 'org', n: '법무부', e: 'Department of Justice', a: ['=DOJ', '=DoJ', 'Department of Justice', 'Justice Department', '법무부'], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'fbi', t: 'org', n: '연방수사국(FBI)', e: 'FBI', a: ['=FBI', '연방수사국'], p: { cat: '연방 민간기관', country: 'us', parent: 'doj' } },
  { id: 'state', t: 'org', n: '국무부', e: 'Department of State', a: ['State Department', 'State Dept', 'Department of State', '국무부', R('(?<![A-Za-z])DoS(?=\\s*-)')], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'doc', t: 'org', n: '상무부', e: 'Department of Commerce', a: ['Department of Commerce', 'Commerce Department', '상무부', '=DoC', '=BIS'], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'nist', t: 'org', n: '국립표준기술연구소(NIST)', e: 'NIST', a: ['=NIST', '국립표준기술연구소'], p: { cat: '연방 민간기관', country: 'us', parent: 'doc' } },
  { id: 'caisi', t: 'org', n: 'AI표준혁신센터(CAISI)', e: 'CAISI', a: ['=CAISI', 'AI 표준·혁신센터', 'AI표준혁신센터', 'Center for AI Standards'], p: { cat: '연방 민간기관', country: 'us', parent: 'nist' } },
  { id: 'uspto', t: 'org', n: '특허청(USPTO)', e: 'USPTO', a: ['=USPTO', '특허청', '특허상표청', '특허 심사'], p: { cat: '연방 민간기관', country: 'us', parent: 'doc' } },
  { id: 'va', t: 'org', n: '보훈부(VA)', e: 'Department of Veterans Affairs', a: ['=VA', '보훈부', '재향군인부', 'Veterans Affairs', '재향군인'], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'hhs', t: 'org', n: '보건복지부(HHS)', e: 'HHS', a: ['=HHS', '보건복지부'], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'fda', t: 'org', n: '식품의약국(FDA)', e: 'FDA', a: ['=FDA', '식품의약국'], p: { cat: '연방 민간기관', country: 'us', parent: 'hhs' } },
  { id: 'doe', t: 'org', n: '에너지부(DOE)', e: 'Department of Energy', a: ['=DOE', '=DoE', 'Department of Energy', 'Energy Department', '에너지부', '국립연구소', 'national laboratory', 'national laboratories', '=LLNL', 'Lawrence Livermore', 'Los Alamos'], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'dot', t: 'org', n: '교통부(DOT)', e: 'Department of Transportation', a: [R('(?<![A-Za-z0-9])(?:DOT|DoT)(?![A-Za-z0-9&])'), 'Department of Transportation', '교통부'], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'faa', t: 'org', n: '연방항공청(FAA)', e: 'FAA', a: ['=FAA', '연방항공청'], p: { cat: '연방 민간기관', country: 'us', parent: 'dot' } },
  { id: 'usda', t: 'org', n: '농무부(USDA)', e: 'USDA', a: ['=USDA', '농무부'], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'opm', t: 'org', n: '인사관리처(OPM)', e: 'OPM', a: ['=OPM', '인사관리처', '인사관리국'], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'ssa', t: 'org', n: '사회보장국(SSA)', e: 'SSA', a: ['=SSA', '사회보장국', '사회보장청'], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'treasury', t: 'org', n: '재무부', e: 'Department of the Treasury', a: ['Treasury', '재무부'], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'nasa', t: 'org', n: 'NASA', e: 'NASA', a: ['=NASA'], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'nara', t: 'org', n: '국가기록원(NARA)', e: 'NARA', a: ['=NARA', '국가기록원', '국가기록청'], p: { cat: '연방 민간기관', country: 'us' } },
  { id: 'gao', t: 'org', n: '회계감사원(GAO)', e: 'GAO', a: ['=GAO', '회계감사원'], p: { cat: '입법·감사', country: 'us' } },
  { id: 'congress', t: 'org', n: '미 의회', e: 'U.S. Congress', a: ['Congress', 'Senate', '=HASC', '=SASC', 'House Armed Services', 'Senate Armed Services', nf('의회'), nf('상원'), nf('하원')], p: { cat: '입법·감사', country: 'us' } },
  { id: 'nato', t: 'org', n: 'NATO', e: 'NATO', a: ['=NATO', '나토'], p: { cat: '국제기구·동맹' } },
  { id: 'eu', t: 'org', n: '유럽연합(EU)', e: 'European Union', a: ['=EU', '유럽연합', 'European Union'], p: { cat: '국제기구·동맹' } },
  { id: 'un', t: 'org', n: '유엔', e: 'United Nations', a: ['유엔', '안보리', 'United Nations', 'Security Council', '=UNSC'], p: { cat: '국제기구' } },
  { id: 'fiveeyes', t: 'org', n: '파이브 아이즈', e: 'Five Eyes', a: ['Five Eyes', '파이브 아이즈', '파이브아이즈'], p: { cat: '국제기구·동맹' } },
  { id: 'pla', t: 'org', n: '중국 인민해방군(PLA)', e: 'PLA', a: ['=PLA', '=PLAAF', '인민해방군', '중국군'], p: { cat: '외국군', country: 'cn' } },
  { id: 'idf', t: 'org', n: '이스라엘군(IDF)', e: 'IDF', a: ['=IDF', '이스라엘군', '이스라엘 방위군'], p: { cat: '외국군', country: 'il' } },
  { id: 'brave1', t: 'org', n: 'Brave1(우크라이나 국방혁신 클러스터)', e: 'Brave1', a: ['Brave1', '브레이브1', '브레이브원'], p: { cat: '외국 국방 기관', country: 'ua' } },
  { id: 'ice', t: 'org', n: '이민세관단속국(ICE)', e: 'ICE', a: ['=ICE', '이민세관단속국'], p: { cat: '연방 민간기관', country: 'us', parent: 'dhs' } },
  { id: 'scsp', t: 'org', n: 'SCSP', e: 'Special Competitive Studies Project', a: ['=SCSP', 'Special Competitive Studies'], p: { cat: '연구기관·싱크탱크', country: 'us' } },
  { id: 'sei', t: 'org', n: 'CMU SEI', e: 'CMU Software Engineering Institute', a: ['=SEI', 'Software Engineering Institute', 'Carnegie Mellon', '카네기멜런', '=CMU'], p: { cat: '연구기관·싱크탱크', country: 'us' } },
  { id: 'mit', t: 'org', n: 'MIT', e: 'MIT', a: ['=MIT', '매사추세츠공대'], p: { cat: '연구기관·싱크탱크', country: 'us' } },
  { id: 'stanford', t: 'org', n: '스탠퍼드대(HAI)', e: 'Stanford University', a: ['Stanford', '스탠퍼드'], p: { cat: '연구기관·싱크탱크', country: 'us' } },
  { id: 'rand', t: 'org', n: 'RAND', e: 'RAND Corporation', a: ['=RAND', '랜드연구소'], p: { cat: '연구기관·싱크탱크', country: 'us' } },
  { id: 'csis', t: 'org', n: 'CSIS', e: 'CSIS', a: ['=CSIS', '전략국제문제연구소'], p: { cat: '연구기관·싱크탱크', country: 'us' } },
  { id: 'cnas', t: 'org', n: 'CNAS', e: 'Center for a New American Security', a: ['=CNAS', '신미국안보센터'], p: { cat: '연구기관·싱크탱크', country: 'us' } },
  { id: 'heritage', t: 'org', n: '헤리티지재단', e: 'Heritage Foundation', a: ['Heritage Foundation', '헤리티지재단', '헤리티지 재단'], p: { cat: '연구기관·싱크탱크', country: 'us' } },

  // ---------------- 기업 ----------------
  { id: 'anthropic', t: 'company', n: 'Anthropic', e: 'Anthropic', a: ['Anthropic', '앤트로픽', '앤스로픽'], p: { cat: '프론티어 AI 랩', country: 'us' } },
  { id: 'openai', t: 'company', n: 'OpenAI', e: 'OpenAI', a: ['OpenAI', '오픈AI', '오픈 AI'], p: { cat: '프론티어 AI 랩', country: 'us' } },
  { id: 'xai', t: 'company', n: 'xAI', e: 'xAI', a: ['=xAI'], p: { cat: '프론티어 AI 랩', country: 'us' } },
  { id: 'google', t: 'company', n: 'Google', e: 'Google', a: ['Google', '구글', 'DeepMind', '딥마인드', 'Alphabet'], p: { cat: '빅테크·클라우드', country: 'us' } },
  { id: 'microsoft', t: 'company', n: 'Microsoft', e: 'Microsoft', a: ['Microsoft', '마이크로소프트', 'Azure', '애저'], p: { cat: '빅테크·클라우드', country: 'us' } },
  { id: 'amazon', t: 'company', n: 'Amazon(AWS)', e: 'Amazon Web Services', a: ['=AWS', 'Amazon', '아마존'], p: { cat: '빅테크·클라우드', country: 'us' } },
  { id: 'meta', t: 'company', n: 'Meta', e: 'Meta', a: ['=Meta', R('메타(?!데이터|버스|인지)')], p: { cat: '빅테크·클라우드', country: 'us' } },
  { id: 'oracle', t: 'company', n: 'Oracle', e: 'Oracle', a: ['Oracle', '오라클'], p: { cat: '빅테크·클라우드', country: 'us' } },
  { id: 'ibm', t: 'company', n: 'IBM', e: 'IBM', a: ['=IBM'], p: { cat: '빅테크·클라우드', country: 'us' } },
  { id: 'nvidia', t: 'company', n: 'NVIDIA', e: 'NVIDIA', a: ['NVIDIA', '엔비디아'], p: { cat: '반도체·인프라', country: 'us' } },
  { id: 'dell', t: 'company', n: 'Dell', e: 'Dell Technologies', a: ['=Dell'], p: { cat: '반도체·인프라', country: 'us' } },
  { id: 'cisco', t: 'company', n: 'Cisco', e: 'Cisco', a: ['Cisco', '시스코'], p: { cat: '반도체·인프라', country: 'us' } },
  { id: 'scaleai', t: 'company', n: 'Scale AI', e: 'Scale AI', a: ['Scale AI', '스케일AI', '스케일 AI'], p: { cat: 'AI 데이터·플랫폼', country: 'us' } },
  { id: 'huggingface', t: 'company', n: 'Hugging Face', e: 'Hugging Face', a: ['Hugging Face', '허깅페이스', '허깅 페이스'], p: { cat: 'AI 데이터·플랫폼', country: 'us' } },
  { id: 'databricks', t: 'company', n: 'Databricks', e: 'Databricks', a: ['Databricks', '데이터브릭스'], p: { cat: 'AI 데이터·플랫폼', country: 'us' } },
  { id: 'cohere', t: 'company', n: 'Cohere', e: 'Cohere', a: ['Cohere', '코히어'], p: { cat: '프론티어 AI 랩', country: 'ca' } },
  { id: 'salesforce', t: 'company', n: 'Salesforce', e: 'Salesforce', a: ['Salesforce', '세일즈포스', 'Missionforce'], p: { cat: '엔터프라이즈 SW', country: 'us' } },
  { id: 'servicenow', t: 'company', n: 'ServiceNow', e: 'ServiceNow', a: ['ServiceNow', '서비스나우'], p: { cat: '엔터프라이즈 SW', country: 'us' } },
  { id: 'palantir', t: 'company', n: 'Palantir', e: 'Palantir', a: ['Palantir', '팔란티어'], p: { cat: '방산 테크', country: 'us' } },
  { id: 'anduril', t: 'company', n: 'Anduril', e: 'Anduril', a: ['Anduril', '안두릴', '앤두릴', '앤듀릴', '앤드루릴', '안듀릴'], p: { cat: '방산 테크', country: 'us' } },
  { id: 'swarmer', t: 'company', n: 'Swarmer', e: 'Swarmer', a: ['Swarmer', '스웜머'], p: { cat: '방산 테크', country: 'ua' } },
  { id: 'golaxy', t: 'company', n: 'GoLaxy', e: 'GoLaxy', a: ['GoLaxy', '골럭시'], p: { cat: '중국 AI', country: 'cn' } },
  { id: 'shieldai', t: 'company', n: 'Shield AI', e: 'Shield AI', a: ['Shield AI', '실드 AI', '쉴드 AI', '실드AI'], p: { cat: '방산 테크', country: 'us' } },
  { id: 'saronic', t: 'company', n: 'Saronic', e: 'Saronic', a: ['Saronic', '사로닉'], p: { cat: '방산 테크', country: 'us' } },
  { id: 'dataminr', t: 'company', n: 'Dataminr', e: 'Dataminr', a: ['Dataminr', '데이터마인르'], p: { cat: '방산 테크', country: 'us' } },
  { id: 'swarmaero', t: 'company', n: 'Swarm Aero', e: 'Swarm Aero', a: ['Swarm Aero', '스웜 에어로'], p: { cat: '방산 테크', country: 'us' } },
  { id: 'neros', t: 'company', n: 'Neros', e: 'Neros', a: ['Neros', '네로스'], p: { cat: '방산 테크', country: 'us' } },
  { id: 'tagup', t: 'company', n: 'Tagup', e: 'Tagup', a: ['Tagup'], p: { cat: '방산 테크', country: 'us' } },
  { id: 'kaizen', t: 'company', n: 'Kaizen Labs', e: 'Kaizen Laboratories', a: ['Kaizen', '카이젠'], p: { cat: '방산 테크', country: 'us' } },
  { id: 'overland', t: 'company', n: 'Overland AI', e: 'Overland AI', a: ['Overland AI', '오버랜드'], p: { cat: '방산 테크', country: 'us' } },
  { id: 'forterra', t: 'company', n: 'Forterra', e: 'Forterra', a: ['Forterra', '포르테라'], p: { cat: '방산 테크', country: 'us' } },
  { id: 'spacex', t: 'company', n: 'SpaceX', e: 'SpaceX', a: ['SpaceX', '스페이스X', 'Starlink', '스타링크', 'Starshield'], p: { cat: '우주', country: 'us' } },
  { id: 'lockheed', t: 'company', n: 'Lockheed Martin', e: 'Lockheed Martin', a: ['Lockheed', '록히드'], p: { cat: '전통 방산', country: 'us' } },
  { id: 'northrop', t: 'company', n: 'Northrop Grumman', e: 'Northrop Grumman', a: ['Northrop', '노스롭'], p: { cat: '전통 방산', country: 'us' } },
  { id: 'ga', t: 'company', n: 'General Atomics', e: 'General Atomics', a: ['General Atomics', '제너럴 아토믹스', '제너럴아토믹스', '=GA-ASI'], p: { cat: '전통 방산', country: 'us' } },
  { id: 'boeing', t: 'company', n: 'Boeing', e: 'Boeing', a: ['Boeing', '보잉'], p: { cat: '전통 방산', country: 'us' } },
  { id: 'rtx', t: 'company', n: 'RTX(Raytheon)', e: 'RTX', a: ['=RTX', 'Raytheon', '레이시온', 'Collins Aerospace', '콜린스 에어로스페이스'], p: { cat: '전통 방산', country: 'us' } },
  { id: 'gd', t: 'company', n: 'General Dynamics', e: 'General Dynamics', a: ['General Dynamics', '제너럴 다이내믹스', '=GDIT'], p: { cat: '전통 방산', country: 'us' } },
  { id: 'l3harris', t: 'company', n: 'L3Harris', e: 'L3Harris', a: ['L3Harris', 'L3해리스'], p: { cat: '전통 방산', country: 'us' } },
  { id: 'leidos', t: 'company', n: 'Leidos', e: 'Leidos', a: ['Leidos', '레이도스'], p: { cat: '전통 방산', country: 'us' } },
  { id: 'boozallen', t: 'company', n: 'Booz Allen Hamilton', e: 'Booz Allen Hamilton', a: ['Booz Allen', '부즈앨런', '부즈 앨런'], p: { cat: '전통 방산', country: 'us' } },
  { id: 'caci', t: 'company', n: 'CACI', e: 'CACI', a: ['=CACI'], p: { cat: '전통 방산', country: 'us' } },
  { id: 'aerovironment', t: 'company', n: 'AeroVironment', e: 'AeroVironment', a: ['AeroVironment', '에어로바이런먼트'], p: { cat: '전통 방산', country: 'us' } },
  { id: 'textron', t: 'company', n: 'Textron', e: 'Textron', a: ['Textron', '텍스트론'], p: { cat: '전통 방산', country: 'us' } },
  { id: 'kratos', t: 'company', n: 'Kratos', e: 'Kratos', a: ['Kratos', '크라토스'], p: { cat: '전통 방산', country: 'us' } },
  { id: 'accenture', t: 'company', n: 'Accenture', e: 'Accenture', a: ['Accenture', '액센츄어'], p: { cat: 'IT 서비스', country: 'us' } },
  { id: 'deloitte', t: 'company', n: 'Deloitte', e: 'Deloitte', a: ['Deloitte', '딜로이트'], p: { cat: 'IT 서비스', country: 'us' } },
  { id: 'thales', t: 'company', n: 'Thales', e: 'Thales', a: ['Thales', '탈레스'], p: { cat: '전통 방산', country: 'fr' } },
  { id: 'saab', t: 'company', n: 'Saab', e: 'Saab', a: ['Saab', '사브'], p: { cat: '전통 방산', country: 'se' } },
  { id: 'rheinmetall', t: 'company', n: 'Rheinmetall', e: 'Rheinmetall', a: ['Rheinmetall', '라인메탈'], p: { cat: '전통 방산', country: 'de' } },
  { id: 'babcock', t: 'company', n: 'Babcock', e: 'Babcock', a: ['Babcock', '밥콕'], p: { cat: '전통 방산', country: 'uk' } },
  { id: 'baykar', t: 'company', n: 'Baykar', e: 'Baykar', a: ['Baykar', '바이카르'], p: { cat: '전통 방산', country: 'tr' } },
  { id: 'deepseek', t: 'company', n: 'DeepSeek', e: 'DeepSeek', a: ['DeepSeek', '딥시크'], p: { cat: '중국 AI', country: 'cn' } },
  { id: 'alibaba', t: 'company', n: 'Alibaba', e: 'Alibaba', a: ['Alibaba', '알리바바', 'Qwen', '큐원'], p: { cat: '중국 AI', country: 'cn' } },
  { id: 'moonshot', t: 'company', n: 'Moonshot AI', e: 'Moonshot AI', a: ['Moonshot', '문샷', 'Kimi'], p: { cat: '중국 AI', country: 'cn' } },
  { id: 'unitree', t: 'company', n: 'Unitree', e: 'Unitree', a: ['Unitree', '유니트리'], p: { cat: '중국 AI', country: 'cn' } },

  // ---------------- AI 모델·제품 ----------------
  { id: 'claude', t: 'model', n: 'Claude', e: 'Claude', a: ['Claude', '클로드'], p: { kind: 'LLM', dev: 'anthropic' } },
  { id: 'mythos', t: 'model', n: 'Claude Mythos', e: 'Claude Mythos', a: ['Mythos', '미토스'], p: { kind: '사이버 특화 프론티어 모델', dev: 'anthropic' } },
  { id: 'fable', t: 'model', n: 'Claude Fable', e: 'Claude Fable', a: ['Fable', '페이블'], p: { kind: 'LLM', dev: 'anthropic' } },
  { id: 'chatgpt', t: 'model', n: 'ChatGPT·GPT', e: 'ChatGPT / GPT', a: ['ChatGPT', '챗GPT', R('(?<![A-Za-z])GPT-\\d')], p: { kind: 'LLM', dev: 'openai' } },
  { id: 'gemini', t: 'model', n: 'Gemini', e: 'Gemini', a: ['Gemini', '제미나이', '제미니'], p: { kind: 'LLM', dev: 'google' } },
  { id: 'grok', t: 'model', n: 'Grok', e: 'Grok', a: ['Grok', '그록'], p: { kind: 'LLM', dev: 'xai' } },
  { id: 'llama', t: 'model', n: 'Llama·Muse', e: 'Llama / Muse Spark', a: ['Llama', 'Muse Spark'], p: { kind: '오픈웨이트 LLM', dev: 'meta' } },
  { id: 'copilot', t: 'model', n: 'Copilot', e: 'Microsoft Copilot', a: ['Copilot', '코파일럿'], p: { kind: 'AI 어시스턴트', dev: 'microsoft' } },
  { id: 'lattice', t: 'model', n: 'Lattice', e: 'Lattice', a: ['=Lattice', '래티스'], p: { kind: '자율·C2 소프트웨어', dev: 'anduril' } },
  { id: 'hivemind', t: 'model', n: 'Hivemind', e: 'Hivemind', a: ['Hivemind', '하이브마인드'], p: { kind: '자율비행 AI', dev: 'shieldai' } },
  { id: 'foundry', t: 'model', n: 'Foundry·AIP', e: 'Palantir Foundry / AIP', a: ['=Foundry', 'Palantir AIP', '=AIP'], p: { kind: '데이터·AI 플랫폼', dev: 'palantir' } },

  // ---------------- 프로그램·체계 ----------------
  { id: 'genaimil', t: 'program', n: 'GenAI.mil', e: 'GenAI.mil', a: ['GenAI.mil', 'GenAI. mil'], p: { cat: 'AI 플랫폼', op: ['dod', 'cdao'], ctr: ['google', 'openai', 'xai'] } },
  { id: 'maven', t: 'program', n: 'Maven Smart System', e: 'Maven Smart System', a: ['Maven', '메이븐'], p: { cat: 'AI 표적·C2 플랫폼', op: ['nga', 'cdao'], ctr: ['palantir'] } },
  { id: 'cca', t: 'program', n: 'CCA(협업전투기)', e: 'Collaborative Combat Aircraft', a: ['=CCA', '=CCAs', 'Collaborative Combat Aircraft', '협동전투기', '협업전투기', '협력전투기', R('(?<![A-Za-z0-9])Y?FQ-4[24]'), R('(?<!Epic\\s?)Fury(?!\\s?(?:작전|Operation))')], p: { cat: '무인 전투기', op: ['usaf'], ctr: ['ga', 'anduril'] } },
  { id: 'mq20', t: 'program', n: 'MQ-20 Avenger', e: 'MQ-20 Avenger', a: [R('(?<![A-Za-z0-9])MQ-20')], p: { cat: '무인 전투기', ctr: ['ga'] } },
  { id: 'arsenal1', t: 'program', n: 'Arsenal-1', e: 'Arsenal-1', a: ['Arsenal-1'], p: { cat: '무기 생산시설', ctr: ['anduril'] } },
  { id: 'ivas', t: 'program', n: 'IVAS Next(EagleEye)', e: 'IVAS Next / EagleEye', a: ['=IVAS', 'EagleEye', '이글아이'], p: { cat: '전투원 증강현실', op: ['army'], ctr: ['anduril', 'meta'] } },
  { id: 'xtech', t: 'program', n: 'xTech', e: 'xTech', a: ['=xTech'], p: { cat: '혁신 경진대회', op: ['army'] } },
  { id: 'dongpt', t: 'program', n: 'DON GPT', e: 'DON GPT', a: ['DON GPT', 'DoN GPT'], p: { cat: '기관 AI 챗봇', op: ['navy'] } },
  { id: 'flankspeed', t: 'program', n: 'Flank Speed', e: 'Flank Speed', a: ['Flank Speed'], p: { cat: '클라우드·협업 환경', op: ['navy'], ctr: ['microsoft'] } },
  { id: 'tmf', t: 'program', n: 'TMF(기술현대화기금)', e: 'Technology Modernization Fund', a: ['=TMF', 'Technology Modernization Fund', '기술현대화기금', '기술 현대화 기금'], p: { cat: 'IT 현대화 기금', op: ['gsa'] } },
  { id: 'mas', t: 'program', n: 'MAS(다수공급일정)', e: 'Multiple Award Schedule', a: ['=MAS', 'Multiple Award Schedule', '다수공급일정', '다중수상일정'], p: { cat: '범정부 조달 계약', op: ['gsa'] } },
  { id: 'mma', t: 'program', n: 'MMA(MQ-9 대체 무인기)', e: 'Massed Modular / Multi-Mission Aircraft', a: ['=MMA', 'Massed Modular Aircraft', 'Multi-Mission Aircraft', '대량 모듈형'], p: { cat: '무인기 획득', op: ['usaf', 'diu'] } },
  { id: 'mq9', t: 'program', n: 'MQ-9 Reaper', e: 'MQ-9 Reaper', a: [R('(?<![A-Za-z0-9])MQ-9'), '=Reaper', '리퍼'], p: { cat: '무인기 플랫폼', op: ['usaf'], ctr: ['ga'] } },
  { id: 'f35', t: 'program', n: 'F-35', e: 'F-35', a: [R('(?<![A-Za-z0-9])F-35')], p: { cat: '유인 전투기', op: ['usaf'], ctr: ['lockheed'] } },
  { id: 'f47', t: 'program', n: 'F-47', e: 'F-47', a: [R('(?<![A-Za-z0-9])F-47')], p: { cat: '6세대 전투기', op: ['usaf'], ctr: ['boeing'] } },
  { id: 'ngc2', t: 'program', n: 'NGC2(차세대 지휘통제)', e: 'Next Generation C2', a: ['=NGC2', 'Next Generation Command and Control', '차세대 지휘통제', '차세대지휘통제'], p: { cat: '지휘통제 체계', op: ['army'], ctr: ['anduril', 'lockheed'] } },
  { id: 'titan', t: 'program', n: 'TITAN', e: 'TITAN', a: ['=TITAN', 'Tactical Intelligence Targeting Access Node'], p: { cat: '지상 정보·표적 노드', op: ['army'], ctr: ['palantir', 'anduril'] } },
  { id: 'jwcc', t: 'program', n: 'JWCC(합동전투클라우드)', e: 'Joint Warfighting Cloud Capability', a: ['=JWCC', 'Joint Warfighting Cloud', 'Joint Warfighter Cloud'], p: { cat: '클라우드 계약', op: ['disa'], ctr: ['amazon', 'microsoft', 'google', 'oracle'] } },
  { id: 'goldendome', t: 'program', n: 'Golden Dome', e: 'Golden Dome', a: ['Golden Dome', '골든 돔', '골든돔'], p: { cat: '미사일 방어', op: ['dod', 'ussf'] } },
  { id: 'replicator', t: 'program', n: 'Replicator', e: 'Replicator', a: ['Replicator', '리플리케이터'], p: { cat: '자율무기 대량배치', op: ['diu'] } },
  { id: 'dawg', t: 'program', n: 'DAWG(국방자율전투그룹)', e: 'Defense Autonomous Warfare Group', a: ['=DAWG', 'Defense Autonomous Warfare Group', '국방자율전투그룹', '국방 자율전투그룹'], p: { cat: '자율무기 대량배치', op: ['dod'] } },
  { id: 'dronedom', t: 'program', n: 'Drone Dominance(드론 우위)', e: 'Drone Dominance', a: ['Drone Dominance', '드론 도미넌스', '드론 우위', 'Gauntlet', '건틀릿'], p: { cat: '드론 획득 사업', op: ['dod', 'army'] } },
  { id: 'dronesmil', t: 'program', n: 'drones.mil(드론 마켓플레이스)', e: 'drones.mil marketplace', a: ['drones.mil', '드론 마켓플레이스', '대드론 마켓플레이스', 'UAS 마켓플레이스', 'Counter-Drone Marketplace', 'drone marketplace'], p: { cat: '디지털 조달 플랫폼', op: ['jiatf401'] } },
  { id: 'blueuas', t: 'program', n: 'Blue UAS', e: 'Blue UAS', a: ['Blue UAS', '블루 UAS'], p: { cat: '드론 인증 목록', op: ['diu'] } },
  { id: 'advana', t: 'program', n: 'Advana', e: 'Advana', a: ['Advana', '어드바나'], p: { cat: '데이터 플랫폼', op: ['cdao'] } },
  { id: 'onegov', t: 'program', n: 'OneGov', e: 'OneGov', a: ['OneGov', '원거브'], p: { cat: '범정부 AI 조달', op: ['gsa'], ctr: ['openai', 'anthropic', 'google'] } },
  { id: 'usai', t: 'program', n: 'USAi', e: 'USAi', a: ['=USAi', 'GSAi'], p: { cat: 'AI 플랫폼', op: ['gsa'] } },
  { id: 'logingov', t: 'program', n: 'Login.gov', e: 'Login.gov', a: ['Login.gov'], p: { cat: '디지털 신원', op: ['gsa'] } },
  { id: 'americagov', t: 'program', n: 'America.gov', e: 'America.gov', a: ['America.gov'], p: { cat: '대국민 AI 포털', op: ['wh'], ctr: ['google', 'xai'] } },
  { id: 'thunderforge', t: 'program', n: 'Thunderforge', e: 'Thunderforge', a: ['Thunderforge', '썬더포지'], p: { cat: 'AI 작전계획', op: ['diu'], ctr: ['scaleai'] } },
  { id: 'genesis', t: 'program', n: 'Genesis Mission', e: 'Genesis Mission', a: ['Genesis Mission', '제네시스 미션'], p: { cat: 'AI 과학 이니셔티브', op: ['doe'] } },
  { id: 'glasswing', t: 'program', n: 'Project Glasswing', e: 'Project Glasswing', a: ['Glasswing', '글래스윙'], p: { cat: 'AI 보안 협력', ctr: ['anthropic'] } },
  { id: 'statechat', t: 'program', n: 'StateChat', e: 'StateChat', a: ['StateChat'], p: { cat: '기관 AI 챗봇', op: ['state'] } },
  { id: 'vagpt', t: 'program', n: 'VA GPT', e: 'VA GPT', a: ['VA GPT'], p: { cat: '기관 AI 챗봇', op: ['va'] } },
  { id: 'dynamis', t: 'program', n: 'Project Dynamis', e: 'Project Dynamis', a: ['Project Dynamis', '다이나미스'], p: { cat: 'JADC2 실험', op: ['usmc'] } },
  { id: 'trex', t: 'program', n: 'T-REX', e: 'T-REX', a: ['T-REX'], p: { cat: '기술 실험' } },
  { id: 'fuze', t: 'program', n: 'FUZE', e: 'FUZE', a: ['=FUZE'], p: { cat: '벤처 투자', op: ['army'] } },

  // ---------------- 정책·법규 ----------------
  { id: 'cmmc', t: 'policy', n: 'CMMC', e: 'Cybersecurity Maturity Model Certification', a: ['=CMMC', 'Cybersecurity Maturity Model', '=C3PAO'], p: { kind: '인증 제도', iss: 'dod' } },
  { id: 'fedramp', t: 'policy', n: 'FedRAMP', e: 'FedRAMP', a: ['FedRAMP', '페드램프'], p: { kind: '인증 제도', iss: 'gsa' } },
  { id: 'rmf', t: 'policy', n: 'RMF·ATO(운영인가)', e: 'RMF / ATO', a: ['=RMF', '=ATO', '=cATO', '=SWFT', 'Authority to Operate', '운영인가', '운영 인가', '운영 승인', 'SP 800-53', '800-53'], p: { kind: '인가 제도', iss: 'dod' } },
  { id: 'ndaa', t: 'policy', n: 'NDAA(국방수권법)', e: 'National Defense Authorization Act', a: ['=NDAA', '국방수권법', 'National Defense Authorization'], p: { kind: '법률', iss: 'congress' } },
  { id: 'ota', t: 'policy', n: 'OTA(기타거래권한)', e: 'Other Transaction Authority', a: ['=OTA', '=OTAs', 'Other Transaction', '기타거래', '기타 거래'], p: { kind: '획득 제도', iss: 'congress' } },
  { id: 'sbir', t: 'policy', n: 'SBIR·STTR', e: 'SBIR / STTR', a: ['=SBIR', '=STTR'], p: { kind: '획득 제도', iss: 'congress' } },
  { id: 'idiq', t: 'policy', n: 'IDIQ 계약', e: 'IDIQ', a: ['=IDIQ'], p: { kind: '계약 방식' } },
  { id: 'far', t: 'policy', n: 'FAR·DFARS(조달규정)', e: 'FAR / DFARS', a: ['=FAR', '=DFARS', 'Federal Acquisition Regulation', '연방조달규정', '연방 조달 규정'], p: { kind: '규정' } },
  { id: 'cso', t: 'policy', n: 'CSO(상업솔루션공모)', e: 'Commercial Solutions Opening', a: [R('(?<![A-Za-z]\\s)CSO(?!\\s[A-Z][a-z])'), 'Commercial Solutions Opening', '상업솔루션', '상용솔루션', '상업 솔루션 공모'], p: { kind: '획득 제도', iss: 'congress' } },
  { id: 'fms', t: 'policy', n: 'FMS(대외군사판매)', e: 'Foreign Military Sales', a: ['=FMS', '대외군사판매', 'Foreign Military Sales'], p: { kind: '획득 제도', iss: 'dod' } },
  { id: 'aiexport', t: 'policy', n: 'AI 풀스택 수출 진흥', e: 'American AI Exports', a: ['AI 수출', '풀스택 AI', 'full-stack AI', 'American AI Exports', 'AI 기술 스택 수출'], p: { kind: '국가 전략', iss: 'doc' } },
  { id: 'cyberaiprofile', t: 'policy', n: 'NIST Cyber AI Profile', e: 'NIST Cyber AI Profile', a: ['Cyber AI Profile', '사이버 AI 프로파일'], p: { kind: '표준·가이드', iss: 'nist' } },
  { id: 'eo', t: 'policy', n: '대통령 행정명령', e: 'Executive Orders', a: ['행정명령', 'Executive Order', '=EO'], p: { kind: '행정명령', iss: 'wh' } },
  { id: 'aiactionplan', t: 'policy', n: 'AI Action Plan', e: "America's AI Action Plan", a: ['AI Action Plan', 'AI 행동계획', 'AI 액션 플랜', 'AI 액션플랜'], p: { kind: '국가 전략', iss: 'wh' } },
  { id: 'ombmemo', t: 'policy', n: 'OMB 메모 M-25-21/22', e: 'OMB M-25-21 / M-25-22', a: ['M-25-21', 'M-25-22'], p: { kind: '행정 지침', iss: 'omb' } },
  { id: 'exportctl', t: 'policy', n: 'AI 반도체 수출통제', e: 'Export controls', a: ['수출통제', '수출 통제', 'export control', 'export controls', '=ITAR'], p: { kind: '규제', iss: 'doc' } },
  { id: 'si', t: 'policy', n: '초지능(SI) 정책', e: 'Super Intelligence policy', a: ['초지능', '슈퍼 인텔리전스', 'Super Intelligence', 'superintelligence', '=ASI'], p: { kind: '행정명령·법안', iss: 'wh' } },
  { id: 'cyberstrat', t: 'policy', n: '사이버 전략(국가·국방)', e: 'Cyber Strategy', a: ['사이버 전략', 'Cyber Strategy', '국가 사이버 전략'], p: { kind: '전략' } },

  // ---------------- 기술 영역 ----------------
  { id: 'd_genai', t: 'domain', n: '생성형 AI·LLM', e: 'Generative AI / LLM', a: ['생성형 AI', '=GenAI', 'Generative AI', '=LLM', '=LLMs', '대형언어모델', '대규모 언어모델', '거대언어모델', '대형 언어모델', '챗봇', 'chatbot', '파운데이션 모델', 'foundation model', '프론티어 AI', '프런티어 AI', 'Frontier AI', '프론티어 모델', '프런티어 모델', 'frontier model', '=RAG'], p: { cat: 'AI 기술' } },
  { id: 'd_agentic', t: 'domain', n: '에이전틱 AI', e: 'Agentic AI', a: ['에이전틱', 'Agentic', '에이전트', 'AI agent', 'AI agents', '=MCP', 'Model Context Protocol', '디지털 직원', 'digital employee', 'digital employees'], p: { cat: 'AI 기술' } },
  { id: 'd_quantum', t: 'domain', n: '양자·PQC', e: 'Quantum / PQC', a: ['양자컴퓨팅', '양자 컴퓨팅', '양자내성', '양자정보', '양자 정보', '양자기술', '양자 기술', '양자 센서', '양자센서', '양자암호', 'quantum', '=PQC', 'post-quantum'], p: { cat: 'AI 기술' } },
  { id: 'd_auto', t: 'domain', n: '자율무기·자율성', e: 'Autonomy', a: ['자율무기', '자율 무기', '자율성', '자율 시스템', '자율체계', '자율 체계', '자율살상', '자율 살상', 'autonomy', 'autonomous', 'Lethal Autonomy', '=LAWS', '자율비행', '자율 비행', '자율주행', '반자율'], p: { cat: '무기·작전' } },
  { id: 'd_uxs', t: 'domain', n: '드론·무인체계', e: 'Drones / Unmanned Systems', a: ['드론', 'drone', 'drones', '=UAS', '=UAV', '=UAVs', '=UGV', '=USV', '=UUV', '=sUAS', '무인기', '무인체계', '무인 체계', '무인수상정', '무인잠수정', '무인지상', 'unmanned', '=FPV', '군집', '스웜', 'swarm', 'swarms', '무인 시스템', '로열 윙맨', '무인 전투기', 'loyal wingman', '무인 수상함'], p: { cat: '무기·작전' } },
  { id: 'd_robot', t: 'domain', n: '로보틱스', e: 'Robotics', a: ['로봇', 'robot', 'robots', 'robotics', '로보틱스', '휴머노이드', 'humanoid'], p: { cat: '무기·작전' } },
  { id: 'd_cuas', t: 'domain', n: '대드론(C-UAS)', e: 'Counter-UAS', a: ['C-UAS', '=cUAS', 'counter-UAS', 'counter-drone', 'counterdrone', '대드론', '드론 방어', '드론 격추', '대무인기', '안티드론', 'anti-drone'], p: { cat: '무기·작전' } },
  { id: 'd_amd', t: 'domain', n: '방공·미사일방어', e: 'Air & Missile Defense', a: ['방공', '미사일 방어', '미사일방어', '요격', 'interceptor', 'interceptors', '=THAAD', 'Patriot', '패트리엇', '패트리어트', 'Iron Dome', '아이언 돔', '지향성 에너지', '지향성에너지', 'directed energy', '레이저 무기', '고출력 마이크로파', '고에너지 레이저'], p: { cat: '무기·작전' } },
  { id: 'd_c2', t: 'domain', n: '지휘통제(C2)·JADC2', e: 'Command & Control / JADC2', a: ['=C2', '지휘통제', '지휘 통제', 'command and control', '=JADC2', '=CJADC2', '킬체인', '킬 체인', '킬웹', 'kill chain', 'kill web', '다영역작전', '다영역 작전', '합동전영역', '=OODA', '=ABMS', '=C3BM', '화력통제', '의사결정 우위'], p: { cat: '무기·작전' } },
  { id: 'd_isr', t: 'domain', n: 'ISR·표적화', e: 'ISR / Targeting', a: ['=ISR', '정찰', '감시정찰', '표적화', 'targeting', '=SIGINT', '=GEOINT', '=OSINT', '신호정보', '위성영상', '위성 영상', '상황인식', '상황 인식', '=ATR', '표적 인식'], p: { cat: '무기·작전' } },
  { id: 'd_ew', t: 'domain', n: '전자전·스펙트럼', e: 'Electronic Warfare', a: ['전자전', 'electronic warfare', '=EW', '재밍', 'jamming', 'jammer', '전자기 스펙트럼', 'electromagnetic spectrum', '=GNSS', 'GPS 거부', 'GPS 재밍', 'GPS-denied'], p: { cat: '무기·작전' } },
  { id: 'd_space', t: 'domain', n: '우주·위성', e: 'Space / Satellites', a: ['위성', 'satellite', 'satellites', R('(?<!항공\\s?)우주(?!\\s?항공)'), '=LEO', '저궤도', '궤도상', 'orbital'], p: { cat: '무기·작전' } },
  { id: 'd_info', t: 'domain', n: '정보·인지전', e: 'Information / Cognitive Warfare', a: [R('정보전(?!략|문|달|송|환|산|파|자|체|면)'), R('인지전(?!략|환|문)'), '딥페이크', 'deepfake', 'deepfakes', '허위정보', 'disinformation', '영향력 공작', '선전물', '선전전', 'propaganda', '가짜뉴스', '가짜 뉴스', '여론전'], p: { cat: '무기·작전' } },
  { id: 'd_logistics', t: 'domain', n: '군수·정비 AI', e: 'Logistics & Sustainment', a: ['군수', '물류', 'logistics', 'sustainment', '예측 정비', '예측정비', 'predictive maintenance', '정비사', '정비창', '정비대대', '정비 소요', '정비 데이터', '정비 인력', '정비·보급', '항공기 정비', '장비 정비', '유지보수', '유지 보수', '=MRO', '탄약', 'munitions'], p: { cat: '무기·작전' } },
  { id: 'd_sim', t: 'domain', n: '워게임·시뮬레이션', e: 'Wargaming & Simulation', a: ['워게임', 'wargame', 'wargaming', '시뮬레이션', 'simulation', '디지털 트윈', 'digital twin', '모의훈련', '=TTX'], p: { cat: '무기·작전' } },
  { id: 'd_cyber', t: 'domain', n: '사이버보안', e: 'Cybersecurity', a: ['사이버보안', '사이버 보안', '사이버안보', '사이버 안보', 'cybersecurity', 'cyber security', '사이버 방어', '사이버방어', '사이버 공격', '사이버공격', 'cyberattack', 'cyberattacks', '해킹', '해커', 'hacker', 'hackers', '랜섬웨어', 'ransomware', '취약점', 'vulnerability', 'vulnerabilities', '제로데이', 'zero-day', '피싱', 'phishing', 'AI 보안', '사이버 AI'], p: { cat: '사이버·인프라' } },
  { id: 'd_zt', t: 'domain', n: '제로트러스트', e: 'Zero Trust', a: ['제로트러스트', '제로 트러스트', 'Zero Trust', '=ZTA', '=ICAM'], p: { cat: '사이버·인프라' } },
  { id: 'd_cloud', t: 'domain', n: '클라우드', e: 'Cloud', a: ['클라우드', 'cloud', '=IL4', '=IL5', '=IL6', 'IL-5', 'GovCloud', 'FinOps', '=SaaS', '하이퍼스케일', '=MNaaS'], p: { cat: '사이버·인프라' } },
  { id: 'd_data', t: 'domain', n: '데이터 통합·거버넌스', e: 'Data Integration & Governance', a: ['데이터 통합', '데이터 거버넌스', '데이터 표준', '데이터 플랫폼', '데이터 메시', '데이터 패브릭', 'data fabric', 'data mesh', '데이터 주권', '데이터 보안', 'data governance', '데이터 레이크', '데이터 공유', 'data sharing', '데이터 전략', '=CUI', '데이터 품질'], p: { cat: '사이버·인프라' } },
  { id: 'd_compute', t: 'domain', n: 'AI 인프라·컴퓨팅', e: 'AI Infrastructure & Compute', a: ['데이터센터', '데이터 센터', 'data center', 'datacenter', '=GPU', '=GPUs', '슈퍼컴퓨터', 'supercomputer', '=HPC', 'AI 인프라', 'AI 컴퓨팅', 'AI 팩토리', '반도체', 'semiconductor', 'semiconductors', 'AI 칩', 'AI chip', 'AI chips'], p: { cat: '사이버·인프라' } },
  { id: 'd_edge', t: 'domain', n: '엣지·DDIL 환경', e: 'Edge / DDIL', a: ['엣지', 'edge computing', 'tactical edge', '=DDIL', '통신 두절', '통신두절', '통신 거부', '통신이 단절'], p: { cat: '사이버·인프라' } },
  { id: 'd_itmod', t: 'domain', n: 'IT 현대화·레거시', e: 'IT Modernization', a: ['레거시', 'legacy', 'IT 현대화', '디지털 전환', '디지털 현대화', 'digital transformation', 'IT modernization', 'IT-as-a-Service'], p: { cat: '사이버·인프라' } },
  { id: 'd_automation', t: 'domain', n: '업무 자동화', e: 'Process Automation', a: ['자동화', 'automation', '=RPA'], p: { cat: '사이버·인프라' } },
  { id: 'd_devsecops', t: 'domain', n: 'SW 획득·DevSecOps', e: 'Software Acquisition / DevSecOps', a: ['=SBOM', 'DevSecOps', '소프트웨어 획득', 'software acquisition', '소프트웨어 팩토리', 'software factory', '소프트웨어 공급망', '=SWP', 'Software Acquisition Pathway', '소프트웨어 조달'], p: { cat: '획득·제도' } },
  { id: 'd_acq', t: 'domain', n: '획득·조달 개혁', e: 'Acquisition Reform', a: ['획득 개혁', '획득개혁', '조달 개혁', '조달 혁신', '획득 혁신', '신속 획득', '신속획득', '획득 주기', '획득 체계', '조달 절차', 'acquisition reform', 'AI 조달', '연방 조달', 'IT 조달', '=PAE', 'Portfolio Acquisition Executive', '포트폴리오 획득', '=ELA', '엔터프라이즈 계약', '엔터프라이즈 라이선스'], p: { cat: '획득·제도' } },
  { id: 'd_open', t: 'domain', n: '상호운용성·개방형 아키텍처', e: 'Interoperability / Open Architecture', a: ['상호운용성', 'interoperability', '=MOSA', 'A-GRA', '개방형 아키텍처', 'open architecture', '멀티벤더', 'multi-vendor', '벤더 종속', 'vendor lock', '플러그 앤 플레이', 'plug-and-play'], p: { cat: '획득·제도' } },
  { id: 'd_budget', t: 'domain', n: '국방 예산·회계연도', e: 'Defense Budget', a: ['FY2026', 'FY2027', 'FY2028', 'FY26', 'FY27', 'FY 2026', 'FY 2027', '국방 예산', '국방예산', '예산안', '예산 요청', '예산요청', 'Reconciliation', 'RDT&E', '추가경정'], p: { cat: '획득·제도' } },
  { id: 'd_startup', t: 'domain', n: '방산 혁신·스타트업', e: 'Defense Innovation & Startups', a: ['방산 혁신', '국방 혁신', '방산 스타트업', '스타트업', 'startup', 'startups', '벤처', 'venture capital', '=VC', '죽음의 계곡', '죽음의계곡', 'valley of death'], p: { cat: '획득·제도' } },
  { id: 'd_supply', t: 'domain', n: '공급망 보안', e: 'Supply Chain Security', a: ['공급망', 'supply chain', 'supply-chain', '희토류', 'rare earth'], p: { cat: '획득·제도' } },
  { id: 'd_gov', t: 'domain', n: 'AI 거버넌스·안전', e: 'AI Governance & Safety', a: [R('(?<!데이터\\s?)거버넌스'), 'AI 안전', 'AI safety', '가드레일', 'guardrail', 'guardrails', 'AI 윤리', '책임 있는 AI', 'Responsible AI', 'AI 규제', 'AI 정책', 'AI 위험', 'AI 리스크', 'AI RMF', '안전장치', 'safeguard', 'safeguards', '규제 완화'], p: { cat: '거버넌스·인력' } },
  { id: 'd_hitl', t: 'domain', n: '인간 통제(HITL)', e: 'Human-in-the-Loop', a: ['Human-in-the-Loop', 'human in the loop', 'Human-on-the-Loop', 'human on the loop', '인간 개입', '인간 통제', '인간 감독', '인간-기계', '인간 중심', '인간의 판단', '=HITL', '=MUM-T', '인간-AI 협업', '인간-AI', '유무인 협업', '유무인 복합'], p: { cat: '거버넌스·인력' } },
  { id: 'd_workforce', t: 'domain', n: 'AI 인력·교육', e: 'AI Workforce & Literacy', a: ['AI 인재', 'AI 인력', 'AI 리터러시', 'AI literacy', 'AI 교육', '재교육', '업스킬', 'upskill', 'upskilling', '해커톤', 'hackathon', '인재 확보', 'workforce'], p: { cat: '거버넌스·인력' } },
  { id: 'd_medical', t: 'domain', n: '의료·헬스 AI', e: 'Healthcare AI', a: ['의료', '헬스케어', 'healthcare', '=EHR', '전자건강기록', '진료', '임상'], p: { cat: '공공 서비스' } },

  // ---------------- 인물 ----------------
  { id: 'p_trump', t: 'person', n: '도널드 트럼프', e: 'Donald Trump', a: ['Trump', '트럼프'], p: { role: '대통령', aff: 'wh' } },
  { id: 'p_vance', t: 'person', n: 'JD 밴스', e: 'JD Vance', a: ['Vance', R('(?<![가-힣])밴스(?!드)')], p: { role: '부통령', aff: 'wh' } },
  { id: 'p_hegseth', t: 'person', n: '피트 헤그세스', e: 'Pete Hegseth', a: ['Hegseth', '헤그세스', '헥세스'], p: { role: '국방(전쟁)장관', aff: 'dod' } },
  { id: 'p_feinberg', t: 'person', n: '스티브 파인버그', e: 'Steve Feinberg', a: ['Feinberg', '파인버그'], p: { role: '국방부 부장관', aff: 'dod' } },
  { id: 'p_michael', t: 'person', n: '에밀 마이클', e: 'Emil Michael', a: ['Emil Michael', '에밀 마이클', '마이클 차관'], p: { role: '연구공학차관(USD R&E)', aff: 'dod' } },
  { id: 'p_stanley', t: 'person', n: '캐머런 스탠리', e: 'Cameron Stanley', a: ['Cameron Stanley', '캐머런 스탠리', '카메론 스탠리'], p: { role: '최고디지털·AI책임자(CDAO)', aff: 'cdao' } },
  { id: 'p_davies', t: 'person', n: '커스틴 데이비스', e: 'Kirsten Davies', a: ['Kirsten Davies', '커스틴 데이비스'], p: { role: '국방부 CIO', aff: 'dod' } },
  { id: 'p_driscoll', t: 'person', n: '댄 드리스콜', e: 'Dan Driscoll', a: ['Driscoll', '드리스콜'], p: { role: '육군장관', aff: 'army' } },
  { id: 'p_meink', t: 'person', n: '트로이 마잉크', e: 'Troy Meink', a: ['Meink', '마잉크', '트로이 밍크'], p: { role: '공군장관', aff: 'usaf' } },
  { id: 'p_davenport', t: 'person', n: '수전 대븐포트', e: 'Susan Davenport', a: ['Susan Davenport', '대븐포트'], p: { role: '공군성 CDAO', aff: 'usaf' } },
  { id: 'p_caine', t: 'person', n: '댄 케인', e: 'Dan Caine', a: ['Caine', '댄 케인', '케인 합참'], p: { role: '합참의장', aff: 'jcs' } },
  { id: 'p_paparo', t: 'person', n: '새뮤얼 파파로', e: 'Samuel Paparo', a: ['Paparo', '파파로'], p: { role: '인도태평양사령관', aff: 'indopacom' } },
  { id: 'p_ross', t: 'person', n: '매트 로스', e: 'Matt Ross', a: ['Matt Ross', '매트 로스'], p: { role: 'JIATF-401 사령관', aff: 'jiatf401' } },
  { id: 'p_cao', t: 'person', n: '훙 카오', e: 'Hung Cao', a: ['Hung Cao', '훙 카오'], p: { role: '해군장관 대행', aff: 'navy' } },
  { id: 'p_arrington', t: 'person', n: '케이티 애링턴', e: 'Katie Arrington', a: ['Arrington', '애링턴'], p: { role: '전 국방부 CISO', aff: 'dod' } },
  { id: 'p_kosiba', t: 'person', n: '팀 코시바', e: 'Tim Kosiba', a: ['Kosiba', '코시바'], p: { role: 'NSA 부국장', aff: 'nsa' } },
  { id: 'p_kratsios', t: 'person', n: '마이클 크라치오스', e: 'Michael Kratsios', a: ['Kratsios', '크라치오스', '크라시오스'], p: { role: 'OSTP 실장', aff: 'ostp' } },
  { id: 'p_cairncross', t: 'person', n: '숀 케른크로스', e: 'Sean Cairncross', a: ['Cairncross', '케른크로스', '캐언크로스'], p: { role: '국가사이버국장', aff: 'oncd' } },
  { id: 'p_barbaccia', t: 'person', n: '그렉 바바치아', e: 'Greg Barbaccia', a: ['Barbaccia', '바바치아'], p: { role: '연방 CIO', aff: 'omb' } },
  { id: 'p_stanton', t: 'person', n: '로라 스탠턴', e: 'Laura Stanton', a: ['Laura Stanton', '로라 스탠턴'], p: { role: 'GSA 연방조달서비스청장', aff: 'gsa' } },
  { id: 'p_lynch', t: 'person', n: '마이클 린치', e: 'Michael Lynch', a: ['Michael Lynch', '마이클 린치'], p: { role: 'GSA 부청장', aff: 'gsa' } },
  { id: 'p_andersen', t: 'person', n: '닉 앤더슨', e: 'Nick Andersen', a: ['Nick Andersen', '닉 앤더슨'], p: { role: 'CISA 국장대행', aff: 'cisa' } },
  { id: 'p_amodei', t: 'person', n: '다리오 아모데이', e: 'Dario Amodei', a: ['Amodei', '아모데이'], p: { role: 'Anthropic CEO', affc: 'anthropic' } },
  { id: 'p_altman', t: 'person', n: '샘 올트먼', e: 'Sam Altman', a: ['Altman', '올트먼'], p: { role: 'OpenAI CEO', affc: 'openai' } },
  { id: 'p_musk', t: 'person', n: '일론 머스크', e: 'Elon Musk', a: ['Musk', '머스크'], p: { role: 'xAI·SpaceX CEO', affc: 'xai' } },
  { id: 'p_luckey', t: 'person', n: '팔머 럭키', e: 'Palmer Luckey', a: ['Luckey', '팔머 럭키'], p: { role: 'Anduril 창립자', affc: 'anduril' } },

  // ---------------- 사건·작전 ----------------
  { id: 'ev_epicfury', t: 'event', n: '이란전(Operation Epic Fury)', e: 'Operation Epic Fury', a: ['Epic Fury', '에픽 퓨리', '에픽퓨리', '대이란', '이란전', '이란 전쟁', '이란 공습', 'Iran war', 'Iran strikes'], p: { kind: '무력 충돌', period: '2026.2~' }, rel: ['ir', 'centcom'] },
  { id: 'ev_ukrwar', t: 'event', n: '러시아-우크라이나 전쟁', e: 'Russia-Ukraine War', a: ['우크라이나전', '우크라이나 전쟁', '러-우', '러시아-우크라이나', 'Russia-Ukraine', 'Ukraine war', '우크라이나 교훈', '우크라이나 전장'], p: { kind: '무력 충돌', period: '2022.2~' }, rel: ['ua', 'ru'] },
  { id: 'ev_anthropic', t: 'event', n: 'Anthropic 공급망 리스크 지정·소송', e: 'Anthropic supply-chain risk dispute', a: [R('공급망\\s?(?:위험|리스크)\\s?(?:기업|업체)?\\s?(?:으로|로)?\\s?지정'), R('supply[- ]chain risk\\s?\\(?(?:Anthropic|designation)', 'i'), 'Supply Risk Designation', 'Anthropic 소송', '앤트로픽 소송', 'Anthropic Workload Migration', '모든 합법적 목적', '수정헌법'], p: { kind: '정책 분쟁·소송', period: '2026.2~' }, rel: ['anthropic', 'dod'] },
  { id: 'ev_contain', t: 'event', n: 'AI 모델 격리 이탈 사건', e: 'AI containment breaches', a: [R('격리\\s?(?:된\\s?)?(?:환경|통제)?\\s?(?:을|를)?\\s?(?:이탈|탈출|우회|벗어)'), '컨테이너 탈출', 'container escape', '샌드박스 탈출', 'sandbox escape', '테스트 환경을 이탈', '테스트 환경 이탈', 'Hugging Face 침해', 'Hugging Face 공격', 'Hugging Face 시스템'], p: { kind: 'AI 안전 사고', period: '2026.7~9' }, rel: ['openai', 'anthropic', 'huggingface'] },
  { id: 'ev_distill', t: 'event', n: '중국의 미 AI 모델 증류', e: 'Model distillation campaign', a: ['증류', 'distillation'], p: { kind: '기술 탈취 공작', period: '2026' }, rel: ['cn', 'deepseek', 'moonshot', 'alibaba'] },
  { id: 'ev_cnhack', t: 'event', n: '중국 연계 사이버 공작', e: 'China-linked cyber operations', a: ['Salt Typhoon', 'Volt Typhoon', '=TA419', 'China-linked', '중국 연계 해킹', '중국 연계 해커', '중국 정부 연계'], p: { kind: '사이버 공작' }, rel: ['cn'] },
  { id: 'ev_dmdc', t: 'event', n: '국방부 DMDC 개인정보 유출', e: 'DMDC data breach', a: ['=DMDC', '인력데이터센터'], p: { kind: '정보 유출', period: '2025.10~2026.7' }, rel: ['dod'] },
  // 컨퍼런스·행사 (발언·발표가 나온 장소)
  { id: 'ev_billington', t: 'event', n: '빌링턴 사이버보안 서밋', e: 'Billington CyberSecurity Summit', a: ['Billington', '빌링턴'], p: { kind: '컨퍼런스·행사' } },
  { id: 'ev_afa', t: 'event', n: 'AFA 항공·우주·사이버 컨퍼런스', e: 'AFA Air, Space & Cyber Conference', a: ['=AFA', 'Air, Space & Cyber', 'Air, Space and Cyber'], p: { kind: '컨퍼런스·행사' }, rel: ['usaf', 'ussf'] },
  { id: 'ev_technet', t: 'event', n: 'AFCEA TechNet', e: 'AFCEA TechNet', a: ['TechNet', '테크넷'], p: { kind: '컨퍼런스·행사' } },
  { id: 'ev_sofweek', t: 'event', n: 'SOF Week', e: 'SOF Week', a: ['SOF Week'], p: { kind: '컨퍼런스·행사' }, rel: ['socom'] },
  { id: 'ev_930gov', t: 'event', n: '930gov 컨퍼런스', e: '930gov', a: ['930gov'], p: { kind: '컨퍼런스·행사' } },
  { id: 'ev_ausa', t: 'event', n: 'AUSA 연례회의', e: 'AUSA Annual Meeting', a: ['=AUSA'], p: { kind: '컨퍼런스·행사' }, rel: ['army'] },
  { id: 'ev_seaairspace', t: 'event', n: 'Sea-Air-Space', e: 'Sea-Air-Space', a: ['Sea-Air-Space', 'Sea Air Space'], p: { kind: '컨퍼런스·행사' }, rel: ['navy'] },
  { id: 'ev_dodiis', t: 'event', n: 'DoDIIS 워크숍', e: 'DoDIIS Worldwide', a: ['=DoDIIS'], p: { kind: '컨퍼런스·행사' }, rel: ['dia'] },
  { id: 'ev_reagan', t: 'event', n: '레이건 국방포럼', e: 'Reagan National Defense Forum', a: ['Reagan National Defense Forum', '레이건 국방포럼', '레이건 국가방위포럼'], p: { kind: '컨퍼런스·행사' } },
  { id: 'ev_farnborough', t: 'event', n: '판버러 에어쇼', e: 'Farnborough Airshow', a: ['Farnborough', '판버러'], p: { kind: '컨퍼런스·행사' }, rel: ['uk'] },
  { id: 'ev_parisair', t: 'event', n: '파리 에어쇼', e: 'Paris Air Show', a: ['Paris Air Show', '파리 에어쇼'], p: { kind: '컨퍼런스·행사' }, rel: ['fr'] },
  { id: 'ev_xiangshan', t: 'event', n: '샹산 포럼', e: 'Xiangshan Forum', a: ['Xiangshan', '샹산'], p: { kind: '컨퍼런스·행사' }, rel: ['cn'] },
];

const SRC_NORM = {
  'SEI/CMU': 'CMU SEI', 'CMU Software Engineering Institute': 'CMU SEI',
  'Air and Space Forces Magazine': 'Air & Space Forces Magazine', 'Defense Scoop': 'DefenseScoop',
  'MilitaryAI': 'Military AI', 'GovExec': 'Government Executive',
  'Defense News (Reuters)': 'Defense News', 'The Defense Post (Reuters)': 'The Defense Post',
  'SCSP (ISF Voices 2026)': 'SCSP', 'Yahoo Finance (Business Wire)': 'Business Wire',
  'af.mil': 'U.S. Air Force', 'Army.mil': 'U.S. Army', 'DoD Press Release': 'U.S. Department of War',
  'DoD (war.gov)': 'U.S. Department of War', 'CIO': 'CIO.com', '종합(Reuters, Business Insider, WSJ)': '종합(Reuters 등)',
};
const SRC_CAT = {
  '국방 전문지': ['Defense One', 'Breaking Defense', 'Defense News', 'Air & Space Forces Magazine', 'DefenseScoop', 'The Defense Post', 'Military Times', 'C4ISRNET', 'Military AI', 'Army Times', 'Air Force Times', 'Army Technology', 'Defence Blog', 'The Aviationist', 'Flight Global', 'RealClearDefense', 'Small Wars Journal', 'SpaceNews'],
  '연방 IT·행정 전문지': ['MeriTalk', 'Nextgov/FCW', 'Federal News Network', 'Government Executive', 'Washington Technology', 'FedScoop', 'GovTech', 'CIO.com', 'ISACA'],
  '정부·공식 발표': ['U.S. Department of War', 'U.S. Air Force', 'U.S. Army', 'GOV.UK', 'UK Parliament', 'NIST', 'DIU', 'GSA 뉴스레터'],
  '싱크탱크·연구기관': ['SCSP', 'CMU SEI', 'CNAS', 'CEPA', 'HCSS', 'Finnish AI Region', 'Foreign Affairs'],
  '기업·보도자료': ['Anthropic', 'Palantir Blog', 'Lockheed Martin', 'GlobeNewswire', 'PR Newswire', 'Business Wire'],
  '블로그·뉴스레터': ['Steve Blank Blog', 'DIIE Substack', 'UnHerd'],
};

const DICT = { VERSION: '2026-10-05', ENTITIES, SRC_NORM, SRC_CAT };
if (typeof module !== 'undefined' && module.exports) module.exports = DICT;
else root.ONTOLOGY_DICT = DICT;
})(typeof window !== 'undefined' ? window : globalThis);
